version: '3.9'
services:
    client:
      container_name: client
      build:
        context: .
        dockerfile: Dockerfile-dev
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - '8082:8080'
      environment: 
        - CHOKIDAR_USEPOLLING=true